services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: dinodb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports: ["5434:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports: ["8081:8080"]
volumes:
  pgdata:
